# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/vivado_pro/project_picture_512x512_rgb2gray/project_picture_512x512_rgb2gray.srcs/sources_1/ip/picture_512x512_r/picture_512x512_r.xci
# IP: The module: 'picture_512x512_r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/vivado_pro/project_picture_512x512_rgb2gray/project_picture_512x512_rgb2gray.srcs/sources_1/ip/picture_512x512_r/picture_512x512_r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture_512x512_r'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Project/vivado_pro/project_picture_512x512_rgb2gray/project_picture_512x512_rgb2gray.srcs/sources_1/ip/picture_512x512_r/picture_512x512_r.xci
# IP: The module: 'picture_512x512_r' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/vivado_pro/project_picture_512x512_rgb2gray/project_picture_512x512_rgb2gray.srcs/sources_1/ip/picture_512x512_r/picture_512x512_r_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture_512x512_r'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
